name: Test
on: [push, pull_request]
jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.vi }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]
        vi: [neovim, vim]
    steps:
      - name: Init git
        run: |
          git config --global user.email vim-jetpack@example.com
          git config --global user.name vim-jetpack

      - name: Clone vim-jetpack
        uses: actions/checkout@v3

      - name: Install Lua
        if: ${{ contains(matrix.os, 'windows') }}
        run: |
          Invoke-WebRequest -Uri https://joedf.ahkscript.org/LuaBuilds/hdata/lua-5.4.4_Win64_bin.zip -OutFile .\Lua.zip
          Expand-Archive .\Lua.zip C:\Lua
          Add-Content $env:GITHUB_PATH C:\Lua

      - name: Install vim-themis
        uses: actions/checkout@v3
        with:
          repository: thinca/vim-themis
          path: vim-themis

      - name: Install ${{ matrix.vi }}
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: stable
          neovim: ${{ matrix.vi == 'neovim' }}

      - name: Run tests
        timeout-minutes: 5
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: ./vim-themis/bin/themis ./test/test.vim
  post-test:
    name: All tests passed
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - run: echo ok
